const CONFIG={spreadsheetId:'1YMQPGC8pWdukQ1sQJ7XDHRPQA3fa2GeSC57ue-tImuU',studentsSheet:'CATEQUIZANDOS',attendanceSheet:'QR ASISTENCIA',cycleStart:'2026-08-31',solemnDates:[]};
function doGet(e){if(e&&e.parameter&&e.parameter.action==='report')return apiResponse_(e);return HtmlService.createHtmlOutputFromFile('Index').setTitle('CATEKIDS · Mis asistencias').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function apiResponse_(e){const cb=String(e.parameter.callback||'catekidsCallback').replace(/[^a-zA-Z0-9_.$]/g,'');let p;try{p={ok:true,data:getReport(e.parameter.code||'')}}catch(x){p={ok:false,error:x.message||String(x)}}return ContentService.createTextOutput(cb+'('+JSON.stringify(p)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}
function getReport(scannedCode){
 const code=key_(scannedCode);if(!code)throw new Error('El QR no contiene un código válido.');const ss=SpreadsheetApp.openById(CONFIG.spreadsheetId);
 const students=ss.getSheetByName(CONFIG.studentsSheet).getDataRange().getDisplayValues(),sh=headerMap_(students[0]);const student=students.slice(1).find(r=>key_(r[sh['CODIGO']])===code);if(!student)throw new Error('No encontramos este código en CATEQUIZANDOS.');
 const attendance=ss.getSheetByName(CONFIG.attendanceSheet).getDataRange().getDisplayValues(),ah=headerMap_(attendance[0]),own=attendance.slice(1).filter(r=>key_(r[ah['CODIGO']])===code),all=attendance.slice(1),tz=ss.getSpreadsheetTimeZone()||'America/Mexico_City',today=todayInTz_(tz),start=parseIso_(CONFIG.cycleStart);
 const weekendEnd=new Date(today);if(today.getDay()===6)weekendEnd.setDate(weekendEnd.getDate()+1);const sundays=weekdayDates_(start,weekendEnd,0),thursdays=weekdayDates_(start,today,4);
 const discovered=all.filter(r=>norm_(r[ah['INCIDENCIA']]).includes('MISA SOLEMNE')).map(r=>parseSheetDate_(r[ah['FECHA']])).filter(Boolean);const solemn=uniqueDates_(CONFIG.solemnDates.map(parseIso_).concat(discovered)).filter(d=>d>=start&&d<=today);
 const matches=(r,text)=>norm_(r[ah['INCIDENCIA']]).includes(text),rowDate=r=>parseSheetDate_(r[ah['FECHA']]);
 const attended=(date,kind)=>own.some(r=>{const d=rowDate(r);if(!d)return false;if(kind==='Misa dominical'){const sat=addDays_(date,-1);return matches(r,'MISA DOMINICAL')&&(sameDay_(d,sat)||sameDay_(d,date))}if(kind==='Hora Santa')return matches(r,'HORA SANTA')&&sameDay_(d,date);return matches(r,'MISA SOLEMNE')&&sameDay_(d,date)});
 const status=(date,kind)=>attended(date,kind)?'asistio':((kind==='Misa dominical'&&date>=today)||sameDay_(date,today)?'pendiente':'falta');
 const categories=[buildCategory_('Misa dominical',sundays,status),buildCategory_('Hora Santa',thursdays,status),buildCategory_('Misa solemne',solemn,status)],counted=categories.reduce((n,c)=>n+c.asistencias+c.faltas,0),yes=categories.reduce((n,c)=>n+c.asistencias,0),events=categories.flatMap(c=>c.eventos).sort((a,b)=>a.iso.localeCompare(b.iso));
 return{nombre:student[sh['NOMBRE DEL ALUMNO']]||student[sh['NOMBRE']]||'',curso:student[sh['CURSO']]||'',grupo:student[sh['CODIGO DE GRUPO']]||'',catequista:student[sh['CATEQUISTA']]||'',santo:student[sh['SANTO DE GRUPO']]||'',asistencias:yes,faltas:categories.reduce((n,c)=>n+c.faltas,0),pendientes:categories.reduce((n,c)=>n+c.pendientes,0),porcentaje:counted?Math.round(yes*1000/counted)/10:0,categorias:categories.map(({eventos,...x})=>x),calendario:events.map(x=>({iso:x.iso,fecha:Utilities.formatDate(parseIso_(x.iso),tz,'dd/MM/yyyy'),tipo:x.tipo,estado:x.estado})),cicloInicio:CONFIG.cycleStart,hoy:dateKey_(today),actualizado:Utilities.formatDate(new Date(),tz,'dd/MM/yyyy HH:mm')};
}
function buildCategory_(tipo,dates,statusFn){const eventos=dates.map(d=>({iso:dateKey_(d),tipo,estado:statusFn(d,tipo)}));return{tipo,programadas:eventos.length,asistencias:eventos.filter(x=>x.estado==='asistio').length,faltas:eventos.filter(x=>x.estado==='falta').length,pendientes:eventos.filter(x=>x.estado==='pendiente').length,eventos}}
function headerMap_(r){return r.reduce((m,v,i)=>(m[norm_(v)]=i,m),{})}function key_(v){return norm_(v).replace(/[^A-Z0-9]/g,'')}function norm_(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase()}function parseIso_(s){const p=String(s).split('-').map(Number);return new Date(p[0],p[1]-1,p[2])}function parseSheetDate_(s){const m=String(s||'').match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?new Date(+m[3],+m[2]-1,+m[1]):null}function todayInTz_(tz){return parseIso_(Utilities.formatDate(new Date(),tz,'yyyy-MM-dd'))}function dateKey_(d){return Utilities.formatDate(d,'America/Mexico_City','yyyy-MM-dd')}function sameDay_(a,b){return dateKey_(a)===dateKey_(b)}function addDays_(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}function uniqueDates_(dates){const m={};dates.filter(Boolean).forEach(d=>m[dateKey_(d)]=d);return Object.keys(m).sort().map(k=>m[k])}function weekdayDates_(start,end,w){const out=[],d=new Date(start);while(d.getDay()!==w)d.setDate(d.getDate()+1);while(d<=end){out.push(new Date(d));d.setDate(d.getDate()+7)}return out}
